In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/color-names/makefile
/kaggle/input/color-names/README.md
/kaggle/input/color-names/license.txt
/kaggle/input/color-names/format-colors
/kaggle/input/color-names/output/colors.json
/kaggle/input/color-names/output/colors.conf
/kaggle/input/color-names/output/colors.csv
/kaggle/input/color-names/output/colors.c
/kaggle/input/color-names/output/colors.xml
/kaggle/input/color-names/output/colors.html
/kaggle/input/color-names/output/colors.sexp
/kaggle/input/color-names/input/wiki-color-list.text
/kaggle/input/kalibrierungsbilder-babinet/DSC03187.JPG
/kaggle/input/kalibrierungsbilder-babinet/DSC03205.JPG
/kaggle/input/kalibrierungsbilder-babinet/DSC03222.JPG
/kaggle/input/kalibrierungsbilder-babinet/DSC03174.JPG
/kaggle/input/kalibrierungsbilder-babinet/DSC03249.JPG
/kaggle/input/kalibrierungsbilder-babinet/DSC03212.JPG
/kaggle/input/kalibrierungsbilder-babinet/DSC03166.JPG
/kaggle/input/kalibrierungsbilder-babinet/DSC03271.JPG
/kaggle/input/kalibrierungsbilder-babinet/DSC032

In [2]:
from PIL import Image
import matplotlib.pyplot as plt
import cv2
import click
import seaborn as sns
import matplotlib.image as img
from tqdm import tqdm_notebook
%matplotlib inline

input = "../input/kalibrierungsbilder-babinet"
!ls "../input/kalibrierungsbilder-babinet"


DSC03132.JPG  DSC03160.JPG  DSC03188.JPG  DSC03216.JPG	DSC03244.JPG
DSC03133.JPG  DSC03161.JPG  DSC03189.JPG  DSC03217.JPG	DSC03245.JPG
DSC03134.JPG  DSC03162.JPG  DSC03190.JPG  DSC03218.JPG	DSC03246.JPG
DSC03135.JPG  DSC03163.JPG  DSC03191.JPG  DSC03219.JPG	DSC03247.JPG
DSC03136.JPG  DSC03164.JPG  DSC03192.JPG  DSC03220.JPG	DSC03248.JPG
DSC03137.JPG  DSC03165.JPG  DSC03193.JPG  DSC03221.JPG	DSC03249.JPG
DSC03138.JPG  DSC03166.JPG  DSC03194.JPG  DSC03222.JPG	DSC03250.JPG
DSC03139.JPG  DSC03167.JPG  DSC03195.JPG  DSC03223.JPG	DSC03251.JPG
DSC03140.JPG  DSC03168.JPG  DSC03196.JPG  DSC03224.JPG	DSC03252.JPG
DSC03141.JPG  DSC03169.JPG  DSC03197.JPG  DSC03225.JPG	DSC03253.JPG
DSC03142.JPG  DSC03170.JPG  DSC03198.JPG  DSC03226.JPG	DSC03254.JPG
DSC03143.JPG  DSC03171.JPG  DSC03199.JPG  DSC03227.JPG	DSC03255.JPG
DSC03144.JPG  DSC03172.JPG  DSC03200.JPG  DSC03228.JPG	DSC03256.JPG
DSC03145.JPG  DSC03173.JPG  DSC03201.JPG  DSC03229.JPG	DSC03257.JPG
DSC03146.JPG  DSC03174.JPG  DSC03202.JPG  DSC032

In [3]:
#Bilder aufrufen
blist = []
for i in range(140):
    i=132+i
    i=str(i)
    bilder = img.imread("../input/kalibrierungsbilder-babinet/DSC03"+i+".JPG")
    
    blist.append(bilder)

#Kontrolle, ob alle Bilder aufgerufen werden
print(len(blist))

140


In [4]:
#Bild darstellen
print(blist[0])

[[[ 82  58  20]
  [ 82  60  21]
  [ 82  60  21]
  ...
  [114  86  38]
  [117  89  41]
  [117  89  41]]

 [[ 82  60  21]
  [ 83  61  22]
  [ 82  60  21]
  ...
  [114  88  39]
  [117  89  41]
  [115  87  39]]

 [[ 82  60  21]
  [ 83  61  22]
  [ 83  61  24]
  ...
  [114  88  39]
  [116  88  40]
  [113  85  37]]

 ...

 [[ 81  54   9]
  [ 79  55  11]
  [ 79  55  11]
  ...
  [ 75  54   9]
  [ 74  53   8]
  [ 72  53  10]]

 [[ 83  56  13]
  [ 84  57  14]
  [ 82  58  14]
  ...
  [ 74  53   8]
  [ 73  52   7]
  [ 71  52   9]]

 [[ 85  58  13]
  [ 84  57  14]
  [ 83  59  15]
  ...
  [ 72  51   6]
  [ 72  51   6]
  [ 68  49   6]]]


In [5]:
#Pixel auslesen
rgb_pixel_values = []
for i in range(140):
    rgb_pixel_values = print (blist[i][3000,1700,:])



[96 60 10]
[110  73  18]
[104  67  14]
[113  73  21]
[95 59  9]
[95 61 16]
[96 62 14]
[104  67  12]
[99 62  9]
[111  75  17]
[115  76  19]
[116  75  19]
[106  70  12]
[104  65  10]
[96 56  4]
[107  68  11]
[108  65  10]
[107  68  11]
[102  65  12]
[116  77  18]
[97 59 12]
[77 45  0]
[87 51  3]
[93 55  6]
[91 55  5]
[94 57  5]
[101  65  13]
[113  78  20]
[109  72  17]
[115  78  23]
[99 63 11]
[111  75  17]
[95 59  7]
[81 51  1]
[92 54  5]
[100  65  11]
[92 59  8]
[105  69  17]
[102  66  14]
[103  67  15]
[103  66  11]
[106  65   9]
[87 51  3]
[107  68  11]
[108  72  14]
[112  76  16]
[108  72  14]
[117  78  19]
[119  81  19]
[110  77  23]
[93 53  1]
[116  76  17]
[116  76  15]
[109  70  13]
[111  72  15]
[107  68  11]
[107  68  13]
[118  79  22]
[115  79  21]
[114  79  21]
[84 51  0]
[118  79  24]
[109  72  19]
[112  73  16]
[109  68  16]
[106  70  12]
[103  66  13]
[105  70  16]
[91 55  3]
[95 58  6]
[97 58  3]
[101  64   9]
[109  72  19]
[103  66  11]
[108  72  12]
[103  63  12]
[105 